### PR TITLE
Support relative binary path

### PR DESCRIPTION
**Pull request by ToQoz**
To use buf installed from @bufbuild/buf in the npm package, it didn't seem to work with the relative path specified.

Since npm packages are usually managed in package.json for each project, the `buf` command is installed in node_modules/.bin/buf. This PR is intended to allow binaryPath relative paths to be specified from the project's .vscode/settings.json.

~Also, the target vscode version was changed to match its type package.~

### CODE REVIEW

**Comment by ToQoz** [comment]
I resolved conflicts with current main branch.

**Review by timosaikkonen — APPROVED** [review]
FWIW, LGTM! Also kinda desperately need this fix.

**Review by paul-sachs — APPROVED** [review]
This looks good to me.

**Comment by paul-sachs** [comment]
Released with 0.6.0 🚀

**Comment by paul-sachs** [comment]
Going to have to revert this change and identify the problem linked in #334

**Pull request merged**
